Added handling of NULL records and un-parseable records.
teragrep/cfe_39 pull request #35
Opened 2024-08-09 10:46 UTC by Tiihott

Added handling of NULL records and un-parseable records.

Partial fix for issue #30.

2024-08-12 12:01 UTC, kortemik requested changes

2024-08-12 12:01 UTC, kortemik commented on src/main/java/com/teragrep/cfe_39/consumers/kafka/DatabaseOutput.java
> +            if (byteArray == null) {
data error must cause a software to abort and abort in a way that it states why it aborted, invalid data must not be processed by default. please create a flag in configuration that allows invalid data to be skipped but logged.

2024-08-12 12:01 UTC, kortemik commented on src/main/java/com/teragrep/cfe_39/consumers/kafka/DatabaseOutput.java
> +            if (byteArray == null) {
this flag should be regarding empty records.

2024-08-12 12:01 UTC, kortemik commented on src/main/java/com/teragrep/cfe_39/consumers/kafka/DatabaseOutput.java
> +            catch (ParseException e) {
invalid data must not be processed, please create a flag that allows parse failures to be skipped but logged.

2024-08-12 12:01 UTC, kortemik commented on src/main/java/com/teragrep/cfe_39/consumers/kafka/HdfsDataIngestion.java
> +            conf.set("hadoop.kerberos.keytab.login.autorenewal.enabled", "true");
make it configureable, please notice that some KDCs allow only limited amount of renewals and have a maximum total renewal time.

2024-08-12 12:01 UTC, kortemik commented on src/test/java/com/teragrep/cfe_39/KafkaConsumerTest.java
> -            Assertions.assertEquals(140, messages.get(0).size() + messages.get(1).size()); // Assert that expected amount of records has been consumed by the consumer group.
why test amounts change?

2024-08-12 13:19 UTC, Tiihott commented on src/main/java/com/teragrep/cfe_39/consumers/kafka/DatabaseOutput.java
> +            if (byteArray == null) {
Added flag for empty records.
Solved in commit 9fb3949e34bc10a6b6c2fd2d21f910ed88402673

2024-08-12 13:19 UTC, Tiihott commented on src/main/java/com/teragrep/cfe_39/consumers/kafka/DatabaseOutput.java
> +            catch (ParseException e) {
Added flag for non RFC5424 records.
Solved in commit 9fb3949e34bc10a6b6c2fd2d21f910ed88402673

2024-08-13 06:38 UTC, Tiihott commented on src/test/java/com/teragrep/cfe_39/KafkaConsumerTest.java
> -            Assertions.assertEquals(140, messages.get(0).size() + messages.get(1).size()); // Assert that expected amount of records has been consumed by the consumer group.
2 new records were added to every test topic partition in MockKafkaConsumerFactory. One null record and one non rfc5424 record. With 10 topic partitions there are now 20 more records in the test data.

2024-08-13 06:46 UTC, Tiihott commented on src/main/java/com/teragrep/cfe_39/consumers/kafka/HdfsDataIngestion.java
> +            conf.set("hadoop.kerberos.keytab.login.autorenewal.enabled", "true");
Added configuration flag for autorenewal in commit 9d4311dda100a56eee0cd1afecc43d43dedb6dec

How should the ticket lifetime problem be approached? Can periodically using checkTGTAndReloginFromKeytab() on the UGI maintain the ticket indefinitely if automatic renewal won't do?

2024-08-20 12:11 UTC, kortemik approved these changes
approved conditionally that code is refactored before merging to main as objectified one.

2024-08-20 12:11 UTC, kortemik commented on src/main/java/com/teragrep/cfe_39/consumers/kafka/DatabaseOutput.java
> +                    throw new NullPointerException("Record with null content detected during processing.");
throw custom exception instead of NPE because the case of null is handled by removing the file.

2024-08-20 12:12 UTC, merged